# Filter
min_particles: 500
max_particles: 2000
kld_err: 0.05
kld_z: 0.99
# minimum distance between particle updates
update_min_d: 0.25
update_min_a: 0.2
# number of filter updates before resampling
resample_interval: 1
# disable filter recovery
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0
# debug
gui_publish_rate: 10.0
# rates
# save_pose_rate: 0.5

# Laser model
laser_model_type: "likelihood_field"
laser_likelihood_max_dist: 2.0
laser_max_beams: 60
# laser_min_range: -1.0
laser_max_range: 12.0
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1

# Odometry model
odom_model_type: "omni"
odom_alpha1: 0.2  # rotation noise per rotation
odom_alpha2: 0.2  # rotation noise per translation
odom_alpha3: 0.2  # translation noise per translation
odom_alpha4: 0.2  # translation noise per rotation
odom_alpha5: 0.1
odom_frame_id: "odom" 
transform_tolerance: 1.0

# # initial pose
# initial_pose_x: 0.0
# initial_pose_y: 0.0
# initial_pose_a: 0.0

use_map_topic: true
