# https://github.com/HBRS-AMR/Robile/blob/main/robile_navigation/robile_navigation_demo/ros/config/move_base_config/global_costmap_params.yaml
global_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 1.0
    static_map: true
    resolution: 0.1