# https://github.com/HBRS-AMR/Robile/blob/main/robile_navigation/robile_navigation_demo/ros/config/move_base_config/costmap_common_params.yaml
obstacle_range: 8.0
raytrace_range: 10.0
footprint: [[-0.33, 0.33], [0.33, 0.33], [0.33, -0.33], [-0.33, -0.33]]
# robot_radius: ir_of_robot
inflation_radius: 0.4

observation_sources: laser_scan_sensor
laser_scan_sensor:
    sensor_frame: base_laser
    data_type: LaserScan
    topic: /scan_filtered
    marking: true
    clearing: true